server:
  servlet:
    context-path: /olwavespring-api
  port: 8080
# Spring properties
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
    name: olwaves
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://ec2-18-215-96-22.compute-1.amazonaws.com:5432/d7gvbt21t337fo
    driver-class-name: org.postgresql.Driver
    username: bgfvynqlyramxc
    password: a84cac44c2af3599b73bc85d2f6cc771efcd2b86c027a099f5df326b93191dd9